### ISSUE TITLE
Look into flakiness

### ISSUE THREAD

**Issue by whitlockjc** [30x/secretrestart#1]
The secret manager seems to fail intermittently and will immediately start working without issue.

**Comment by noahdietz** [comment]
Started by tightening the `SECRET_REFRESH_INTERVAL` of the `secret-generator` from `6h` to `2h` in both e2e and prod.

**Comment by noahdietz** [comment]
image building has been stable thus far, no occurrences of image push failure. Closing. If the issue reappears, I will reopen
